on:
  push:
  # Sequence of patterns matched against refs/tags
    branches:
    - github-actions-test

jobs:

    import: 
        name: Import Apple Signing Certificate
        runs-on: macOS-latest
        steps: 
        # - uses: actions/checkout@v2
        - uses: apple-actions/import-codesign-certs@v1
          with: 
            p12-file-base64: ${{ secrets.APPLE_DEVELOPER_ID_CERT_P12 }}
            p12-password: ${{ secrets.APPLE_DEVELOPER_ID_CERT_PASSWD }}

        - run: security find-identity -v