on:
  push:
  # Sequence of patterns matched against refs/tags
    branches:
    - github-actions-test

jobs:

    notarization: 
        name: Test notarization config adjustment
        runs-on: macOS-latest
        steps: 
        - uses: actions/checkout@v2
        - run: npm install --global json
        - name: Update DMG Name in Notarization config
          run:  json -I -f scripts/gon-dmg.json -e "this.notarize[0].path='File Summoner $(cat ./version).dmg'"